name:                partialord
version:             0.0.1
github:              "jcranch/partialord"
license:             BSD-3-Clause
author:              "James Cranch"
maintainer:          "j.d.cranch@sheffield.ac.uk"
copyright:           "2023 James Cranch"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            Data structure supporting partial orders
category:            Data structures

description:         Please see README.md

dependencies:
- base       >= 4.7 && < 5
- containers >= 0.6 && < 0.8

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  partialord-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - partialord
    - hspec        >= 2.7     && < 2.12
